<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GG0PK5N" failures="1" tests="8" name="Automation Tests" time="13.672" errors="0" timestamp="2024-07-28T16:59:14 EEST">
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.229"/>
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.206"/>
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.242">
    <failure type="java.lang.AssertionError" message="Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at testcases.LoginSauce.loginTest(LoginSauce.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.22"/>
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.23"/>
  <testcase classname="testcases.SauceDemo" name="checkItems" time="0.834"/>
  <testcase classname="testcases.SauceDemo" name="checkCart" time="0.295"/>
  <testcase classname="testcases.SauceDemo" name="checkRemoveButton" time="0.421"/>
</testsuite> <!-- Automation Tests -->
