<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GG0PK5N" failures="1" tests="9" name="Automation Tests" time="16.054" errors="0" timestamp="2024-07-31T18:02:26 EEST">
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.254"/>
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.227"/>
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.249">
    <failure type="java.lang.AssertionError" message="Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at testcases.LoginSauce.loginTest(LoginSauce.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.224"/>
  <testcase classname="testcases.LoginSauce" name="loginTest" time="0.215"/>
  <testcase classname="testcases.SauceDemo" name="checkItems" time="0.861"/>
  <testcase classname="testcases.SauceDemo" name="checkCart" time="0.29"/>
  <testcase classname="testcases.SauceDemo" name="checkRemoveButton" time="0.303"/>
  <testcase classname="testcases.SelectButtonSauce" name="itemSorting" time="0.636"/>
</testsuite> <!-- Automation Tests -->
