<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GG0PK5N" failures="1" tests="9" name="Automation Tests" time="15.472" errors="0" timestamp="2024-08-24T13:38:13 EEST">
  <testcase classname="testcases.LoginSauceTest" name="loginTest" time="0.195"/>
  <testcase classname="testcases.LoginSauceTest" name="loginTest" time="0.221"/>
  <testcase classname="testcases.LoginSauceTest" name="loginTest" time="0.25">
    <failure type="java.lang.AssertionError" message="Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at testcases.LoginSauceTest.loginTest(LoginSauceTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="testcases.LoginSauceTest" name="loginTest" time="0.201"/>
  <testcase classname="testcases.LoginSauceTest" name="loginTest" time="0.22"/>
  <testcase classname="testcases.SauceDemo" name="checkItems" time="0.806"/>
  <testcase classname="testcases.SauceDemo" name="checkCart" time="0.303"/>
  <testcase classname="testcases.SauceDemo" name="checkRemoveButton" time="0.326"/>
  <testcase classname="testcases.SelectButtonSauce" name="itemSorting" time="0.588"/>
</testsuite> <!-- Automation Tests -->
